export const ROLES = {
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER'
};

export const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  DISABLED: 'DISABLED'
};

export const INTEREST_TYPES = {
  REDUCING: 'REDUCING',
  FLAT: 'FLAT'
};

export const CONTRIBUTION_STATUS = {
  PAID: 'PAID',
  PENDING: 'PENDING',
  OVERDUE: 'OVERDUE'
};

export const LOAN_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED'
};

export const INSTALLMENT_STATUS = {
  UPCOMING: 'UPCOMING',
  DUE: 'DUE',
  PAID: 'PAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  OVERDUE: 'OVERDUE'
};

export const TRANSACTION_TYPES = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE'
};

export const TRANSACTION_CATEGORIES = {
  MEMBER_CONTRIBUTION: 'MEMBER_CONTRIBUTION',
  LOAN_DISBURSEMENT: 'LOAN_DISBURSEMENT',
  LOAN_REPAYMENT_PRINCIPAL: 'LOAN_REPAYMENT_PRINCIPAL',
  LOAN_INTEREST: 'LOAN_INTEREST',
  GROUP_EXPENSE: 'GROUP_EXPENSE',
  OTHER_REVENUE: 'OTHER_REVENUE',
  FINE: 'FINE'
};
